--Soal 5a
select p.POLICY_NUMBER,p.POLICY_SUBMIT_DATE,TO_CHAR(p.PREMIUM, 'FM999,999,999.00') as premium,p.DISCOUNT,TO_CHAR(p.COMMISSION, 'FM999,999,999.00') as commission,c.CLIENT_NAME,c.BIRTH_DATE,p.POLICY_STATUS,p.POLICY_DUE_DATE
from T_POLICY p join T_CLIENT c
on c.CLIENT_NUMBER=p.CLIENT_NUMBER
WHERE p.POLICY_SUBMIT_DATE > '2018-01-15' AND EXTRACT(MONTH FROM c.BIRTH_DATE)=9;

--Soal 5b
select p.POLICY_NUMBER,p.POLICY_SUBMIT_DATE,TO_CHAR(p.PREMIUM, 'FM999,999,999.00') as premium,p.DISCOUNT,TO_CHAR(p.COMMISSION, 'FM999,999,999.00') as commission,a.AGENT_NAME,a.AGENT_OFFICE,p.POLICY_STATUS,p.POLICY_DUE_DATE
from T_POLICY p join T_AGENT a
on a.AGENT_CODE=p.AGENT_CODE
WHERE p.POLICY_STATUS='INFORCE' and a.AGENT_OFFICE='JAKARTA'

--Soal 5c
select POLICY_NUMBER,POLICY_SUBMIT_DATE,TO_CHAR(PREMIUM, 'FM999,999,999.00') as premium,DISCOUNT,TO_CHAR(COMMISSION, 'FM999,999,999.00') as commission,(COMMISSION/PREMIUM)*100::FLOAT AS Basic_Commission,POLICY_STATUS,POLICY_DUE_DATE
from T_POLICY 


--Soal 5d
UPDATE T_POLICY SET POLICY_DUE_DATE = POLICY_SUBMIT_DATE + INTERVAL '30 DAY' WHERE POLICY_NUMBER='001';
UPDATE T_POLICY SET POLICY_DUE_DATE = POLICY_SUBMIT_DATE + INTERVAL '30 DAY' WHERE POLICY_NUMBER='002';
UPDATE T_POLICY SET POLICY_DUE_DATE = POLICY_SUBMIT_DATE + INTERVAL '30 DAY' WHERE POLICY_NUMBER='003';
UPDATE T_POLICY SET POLICY_DUE_DATE = POLICY_SUBMIT_DATE + INTERVAL '30 DAY' WHERE POLICY_NUMBER='004';
UPDATE T_POLICY SET POLICY_DUE_DATE = POLICY_SUBMIT_DATE + INTERVAL '30 DAY' WHERE POLICY_NUMBER='005';

--Soal 5e
select a.AGENT_CODE,p.POLICY_NUMBER,c.CLIENT_NUMBER,TO_CHAR(p.PREMIUM, 'FM999,999,999.00') AS Premium,TO_CHAR(((p.DISCOUNT::float/100)*p.PREMIUM), 'FM999,999,999.00') AS PREMIUM_10_PERSEN
from T_POLICY p join T_AGENT a
on a.AGENT_CODE=p.AGENT_CODE
join T_CLIENT c
on c.CLIENT_NUMBER=p.CLIENT_NUMBER
where ((p.DISCOUNT::float/100)*p.PREMIUM)<1000000
order by ((p.DISCOUNT::float/100)*p.PREMIUM) asc






